DROP TABLE Customer;
DROP TABLE Address;

CREATE TABLE Customer (
id            INT NOT NULL NOT NULL AUTO_INCREMENT,
name          VARCHAR(255) NOT NULL,
PRIMARY KEY (id)
);

CREATE TABLE Address (
id          INT NOT NULL AUTO_INCREMENT,
address     VARCHAR(20) NOT NULL,
country     VARCHAR(20) NOT NULL,
PRIMARY KEY (id)
);
